apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: "%APP_NAME%"
  labels:
    cloud.googleapis.com/location: europe-west1
  annotations:
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      serviceAccountName: 490485668008-compute@developer.gserviceaccount.com
      containers:
        - name: customer-service
          image: "%IMAGE%"
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: MODE
              value: dev
            - name: GCP_PROJECT_ID
              value: verifire-60d1b
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /app/secret/verifire-service-account-json
            - name: PRJCT_SERVICE_GRPC_ADDR
              value: project-service-grpc-244108678816.europe-west1.run.app:443
            - name: SBS_SERVICE_GRPC_ADDR
              value: subscription-service-grpc-244108678816.europe-west1.run.app:443
            - name: CHKML_SERVICE_GRPC_ADDR
              value: checkmail-service-grpc-244108678816.europe-west1.run.app:443
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - name: verifire-service-account-json
              mountPath: /app/secret
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8080
      volumes:
        - name: verifire-service-account-json
          secret:
            secretName: verifire-service-account-json
            items:
              - key: latest
                path: verifire-service-account-json
  traffic:
    - percent: 100
      latestRevision: true