package main

import (
	_ "github.com/aerosystems/user-service/docs" // docs are generated by Swag CLI, you have to import it.
	middleware "github.com/aerosystems/user-service/internal/middleware"
	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"
)

func (app *Config) NewRouter() *echo.Echo {
	e := echo.New()

	docsGroup := e.Group("/docs")
	docsGroup.Use(middleware.BasicAuthMiddleware)
	docsGroup.GET("/*", echoSwagger.WrapHandler)

	return e
}
