// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},"swagger":"2.0","info":{"description":"{{escape .Description}}","title":"{{.Title}}","contact":{"name":"Artem Kostenko","url":"https://github.com/aerosystems"},"license":{"name":"Apache 2.0","url":"https://www.apache.org/licenses/LICENSE-2.0.html"},"version":"{{.Version}}"},"host":"{{.Host}}","basePath":"{{.BasePath}}","paths":{"/v1/firebase/create-customer":{"post":{"description":"Create user","consumes":["application/json"],"produces":["application/json"],"tags":["users"],"summary":"Create user","parameters":[{"description":"Create user","name":"raw","in":"body","required":true,"schema":{"$ref":"#/definitions/HTTPServer.CreateFirebaseCustomerRequestBody"}}],"responses":{"204":{"description":"No Content"},"400":{"description":"Bad Request","schema":{"$ref":"#/definitions/HTTPServer.ErrorResponse"}},"422":{"description":"Unprocessable Entity","schema":{"$ref":"#/definitions/HTTPServer.ErrorResponse"}},"500":{"description":"Internal Server Error","schema":{"$ref":"#/definitions/HTTPServer.ErrorResponse"}}}}}},"definitions":{"HTTPServer.CreateFirebaseCustomerRequestBody":{"type":"object","properties":{"message":{"type":"object","properties":{"data":{"type":"array","items":{"type":"integer"}}}},"subscription":{"type":"string"}}},"HTTPServer.ErrorResponse":{"type":"object","properties":{"message":{"type":"string"}}}},"securityDefinitions":{"BearerAuth":{"description":"Should contain Access JWT Token, with the Bearer started","type":"apiKey","name":"Authorization","in":"header"}}}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.1",
	Host:             "gw.verifire.dev/customer",
	BasePath:         "/",
	Schemes:          []string{"https"},
	Title:            "Customer Service",
	Description:      "A part of microservice infrastructure, who responsible for customer user entity.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
